-- Q10: Find total revenue generated by each customer
SELECT 
    customers.name AS customer_name,
    SUM(order_items.unit_price * order_items.quantity) AS total_revenue
FROM customers
JOIN orders 
    ON customers.customer_id = orders.customer_id
JOIN order_items 
    ON orders.order_id = order_items.order_id
GROUP BY customers.customer_id, customers.name
ORDER BY total_revenue DESC;